spring:
  datasource:
    url: jdbc:mysql:///test00
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123123
  thymeleaf:
    mode: HTML5
    cache: false
  cache:
    ehcache:
      config: classpath:com/cnf/ehcache.xml
    type: ehcache
mybatis:
  type-aliases-package: com.example.pojo
  mapper-locations: com/mapper/*.xml
server:
  port: 80
logging:
  level:
    com.example.dao: DEBUG